= Brouwer's theorems

+ We show that given any pair of endomaps $f, g : D arrow.r D$ such that $g compose j = j$, if for all $x in D$, $f(g(x)) eq.not g(x)$, then there exists a continuous retraction of $j$ to the disk's boundary $C$. We use the same construction as the proof for the fixed point theorem, drawing a ray from $f(g(x))$ to $g(x)$ and setting the point the ray intersects the disk to be $r(x)$. The constructed map $r$ will then be a continous retraction of $j$, which we know to be a contradiction.

+ Take any $g : A compose A$, and consider the map $s compose g compose r : X arrow.r X$. By assumption, because $s compose g compose r$ is an endomap from $X$ to $X$, there exists an $x : T arrow.r X$ such that $s compose g compose r compose x = x$. Compose $r$ on the right for both sides of the equality. The left hand side of the equality simplifies to become $r compose s compose g compose r compose x = 1_A compose g compose r compose x = g compose r compose x$, while the right hand side of the equality becomes $r compose x$. This shows that $r compose x$ is a fixed point of $g$.

+ We show this just for the circle. From the fixed point theorem, we know that any continuous endomap of the disk $D$ must have a fixed point $x$. Let $A$ be the antipodal map of the circle mapping each point to its diametrically opposite point, which does not have a fixed point. This means that the assumption of exercise 2 cannot hold: there cannot be a continous map that is a retraction for a map from the circle to the disk.

+ a) I take $E$ to be the object representing start and end times of the trip, $I$ to be the times within the trip (inclusive of the ends), and $R$ to be the physical road. Then, the only map $j : E arrow.r I$ is the inclusion map of the endpoints into the timeframe. Similarly, the maps $m : I arrow.r R$ represent where the author is at each point in time on the trip, and the map $y : I arrow.r R$ represents where I am at each point in time on the trip. To express that the author started at Buffalo and ended at Rochester, there then must exist a map $"start" : bold(1) arrow.r E$ and $"end" : bold(1) arrow.r E$ such that $m compose j compose "start" = "Buffalo"$ and $m compose j compose "end" = "Rochester"$ (where Buffalo and Rochester are the corresponding maps from $bold(1)$).

  b) The conclusion that we meet categorically is as follows. There exists a map $t : bold(1) arrow.r I$ such that $m compose t = y compose t$.
